CREATE TABLE Categories(
	CategoryID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(15) NOT NULL,
	Description NVARCHAR(1000) NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);