CREATE TABLE Cities(
    CityID INT PRIMARY KEY IDENTITY(1,1),
	CountryID INT NOT NULL REFERENCES Countries(CountryID),
    Name NVARCHAR(100) NOT NULL,
	PostCode NVARCHAR(20) NOT NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);