CREATE TABLE Customers(
    CustomerID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(40) NOT NULL,
	AddressLine1 NVARCHAR(100) NOT NULL,
	AddressLine2 NVARCHAR(100) NULL,
	CityID INT NOT NULL REFERENCES Cities(CityID),
	Phone VARCHAR(24) NOT NULL,
	Email VARCHAR(50) NOT NULL CHECK(Email LIKE '%_@__%.__%'),
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);