CREATE TABLE Products(
    ProductID INT PRIMARY KEY IDENTITY(1,1),
	CategoryID INT NOT NULL REFERENCES Categories(CategoryID),
	Barcode VARCHAR(100) NOT NULL UNIQUE,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(1000) NULL,
    Dimensions NVARCHAR(255) NOT NULL,
    Weight FLOAT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);