CREATE TABLE Slots(
    SlotID INT PRIMARY KEY IDENTITY(1,1),
	StorageID INT NOT NULL REFERENCES Storages(StorageID),
	SlotCode VARCHAR(50) NOT NULL UNIQUE,
	IsActive BIT NOT NULL DEFAULT(1),
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateDate DATETIME NULL
);